### ISSUE TITLE
what this project is about?

### ISSUE THREAD

**Issue by lorvent** [Nur1Labs/oldrubychan#2]
Hello,

i don't get what this project is about?

is it updated code of cryptonotefoundation starter code?

or something else?

**Comment by FndNur1Labs** [comment]
yes is updates. since this old one v2 is better. for platform them easy
used. and without bug...

**Comment by Shiro20** [comment]
code improve since start we do better on V2 take a look head 

https://github.com/FndNur1Labs/CryptonoteEvo
